name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@v4
      - name: Install deps
        run: |
          uv venv
          uv sync --group dev
      - name: Lint
        run: |
          uvx ruff check .
          uvx black --check .
          uvx isort --check-only .
      - name: Test
        run: uv run pytest -q
